# Generated by Django 6.0.2 on 2026-03-10 07:06

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import shrishant_dev.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text="Category display label e.g. 'Frontend Engineering'.", max_length=160, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Auto-generated; do not edit after creation.', max_length=180, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Optional rich-text description for the category page.')),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description for the category page (plain text, ≤160 chars).', max_length=160, validators=[django.core.validators.MaxLengthValidator(160)])),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
                'db_table': 'shrishant_blogcategory',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Tag display label.', max_length=80, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Auto-generated; do not edit after creation.', max_length=100, unique=True)),
                ('color_hex', models.CharField(default='#3b82f6', help_text="Hex colour for the tag UI pill e.g. '#3b82f6'.", max_length=7)),
            ],
            options={
                'verbose_name': 'Blog Tag',
                'verbose_name_plural': 'Blog Tags',
                'db_table': 'shrishant_blogtag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Certificate or achievement name.', max_length=200)),
                ('issuer', models.CharField(help_text="Awarding body e.g. 'freeCodeCamp', 'Meta'.", max_length=200)),
                ('issued_date', models.DateField(blank=True, help_text='Date the certificate was issued.', null=True)),
                ('credential_url', models.URLField(blank=True, help_text='Public verification or credential URL.')),
                ('image', models.ImageField(blank=True, help_text='Certificate image or digital badge.', upload_to='shrishant/certifications/')),
            ],
            options={
                'verbose_name': 'Certification',
                'verbose_name_plural': 'Certifications',
                'db_table': 'shrishant_certification',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Entry heading e.g. 'B.Sc. Computer Science — Tribhuvan University'.", max_length=200)),
                ('institution', models.CharField(help_text='University, college, or school name.', max_length=200)),
                ('degree', models.CharField(blank=True, help_text='Degree or qualification type e.g. "Bachelor\'s".', max_length=100)),
                ('field_of_study', models.CharField(blank=True, help_text="Subject area e.g. 'Computer Science'.", max_length=200)),
                ('start_date', models.DateField(help_text='Programme start date (day value is ignored).')),
                ('end_date', models.DateField(blank=True, help_text='Graduation or end date. Leave blank if still ongoing.', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional notes, achievements, or academic highlights.')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'db_table': 'shrishant_education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Entry heading e.g. 'Frontend Developer at Acme Corp'.", max_length=200)),
                ('company', models.CharField(help_text='Company or organisation name.', max_length=200)),
                ('role', models.CharField(help_text='Specific role/position title held at this company.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Key responsibilities and achievements.')),
                ('start_date', models.DateField(help_text='Month/year the role started (day value is ignored).')),
                ('end_date', models.DateField(blank=True, help_text='Month/year the role ended. Leave blank when is_current=True.', null=True)),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text="Check if this is your current job. Displays 'Present' on frontend.")),
                ('company_url', models.URLField(blank=True, help_text='Company website URL.')),
                ('location', models.CharField(blank=True, help_text="City/country or 'Remote'.", max_length=200)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'db_table': 'shrishant_experience',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Project name displayed on the portfolio.', max_length=200)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Rich-text project description. Supports code blocks, links, lists.')),
                ('thumbnail', models.ImageField(blank=True, help_text='Cover image for the project card. Recommended: 16:9 ratio.', upload_to='shrishant/projects/thumbnails/')),
                ('github_url', models.URLField(blank=True, help_text='Public GitHub repository URL.')),
                ('live_url', models.URLField(blank=True, help_text='Live deployment or demo URL.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], db_index=True, default='active', help_text='Active = shown on portfolio. Archived = hidden from public.', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Pin this project to the featured projects section.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Manual display order. Lower = first. 0 = use default ordering.')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'shrishant_project',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Category label shown on the portfolio (e.g. 'Frontend').", max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order — lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'db_table': 'shrishant_skillcategory',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Gallery image. Recommended: high-res screenshot or mockup.', upload_to='shrishant/projects/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional short description of this image.', max_length=300)),
                ('alt_text', models.CharField(blank=True, help_text='Accessibility alt text for screen readers and SEO.', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in the gallery. Lower = first.')),
                ('project', models.ForeignKey(help_text='The project this gallery image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shrishant_dev.project')),
            ],
            options={
                'verbose_name': 'Project Image',
                'verbose_name_plural': 'Project Images',
                'db_table': 'shrishant_projectimage',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Tool or skill name (e.g. 'React').", max_length=100)),
                ('icon', models.ImageField(blank=True, help_text='Icon image. Recommended: SVG/PNG, square, transparent bg.', upload_to='shrishant/techstack/icons/')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show this skill in the featured / hero skills section.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within the category. Lower = first.')),
                ('category', models.ForeignKey(help_text='Category this tool or skill belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='skills', to='shrishant_dev.skillcategory')),
            ],
            options={
                'verbose_name': 'Tech Stack / Skill',
                'verbose_name_plural': 'Tech Stack / Skills',
                'db_table': 'shrishant_techstack',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, help_text='Technologies used in this project.', related_name='projects', to='shrishant_dev.techstack'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, help_text='Post headline.', max_length=200)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Auto-generated; do not edit after creation.', max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short plain-text summary (≤500 chars) for cards and meta previews.', max_length=500)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Full rich-text post body. Supports code blocks, tables, images.')),
                ('hero_image', models.ImageField(blank=True, help_text='Cover image. Recommended: 1200×630 px for social sharing.', null=True, upload_to=shrishant_dev.models._blog_hero_upload_path)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Feature this post as the hero post. Only one post is featured at a time.')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title override (≤60 chars). Falls back to title if blank.', max_length=60, validators=[django.core.validators.MaxLengthValidator(60)])),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description (≤160 chars). Falls back to excerpt if blank.', max_length=160, validators=[django.core.validators.MaxLengthValidator(160)])),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for Facebook/LinkedIn (≤95 chars). Falls back to title.', max_length=95)),
                ('og_description', models.CharField(blank=True, help_text='Open Graph description (≤200 chars). Falls back to meta_description.', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', help_text='Draft = not public. Published = live on the blog.', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, help_text='Auto-set when first published. Override to backdate.', null=True)),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Page view counter incremented on each visit.')),
                ('categories', models.ManyToManyField(blank=True, help_text='Topic categories for content clustering and SEO authority.', related_name='posts', to='shrishant_dev.blogcategory')),
                ('related_posts', models.ManyToManyField(blank=True, help_text='Manually curated related posts shown at the bottom of the post.', related_name='related_to', to='shrishant_dev.blogpost')),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags for fine-grained classification and related content discovery.', related_name='posts', to='shrishant_dev.blogtag')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'shrishant_blogpost',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='shrishant_b_status_eba694_idx'), models.Index(fields=['is_featured', 'status'], name='shrishant_b_is_feat_ccae96_idx'), models.Index(fields=['slug'], name='shrishant_b_slug_79bf12_idx'), models.Index(fields=['-view_count'], name='shrishant_b_view_co_f79a32_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='techstack',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='shrishant_unique_skill_per_category'),
        ),
    ]
